import {getDocument,createDocument,listDocumentsByField,setDocument} from "@/backend/firebase/firestore";
import {getAdminStorageBucket} from "@/backend/firebase/storage";
import type {Report} from "@/types/report";import type {ReportAnalysis} from "@/types/reportAnalysis";
async function verify(reportId:string,doctorId:string){const r=await getDocument<Report>("reports",reportId);if(!r)throw new Error("Report not found.");const p=await getDocument<{doctorId:string}>("patients",r.patientId);if(!p||p.doctorId!==doctorId)throw new Error("Report not found.");if(!r.storagePath)throw new Error("Report file is not available.");return r;}
function schema(){return {type:"object",properties:{summary:{type:"string"},observations:{type:"array",items:{type:"string"}},documentedChanges:{type:"array",items:{type:"string"}},limitations:{type:"array",items:{type:"string"}}},required:["summary","observations","documentedChanges","limitations"]};}
export async function generateReportAnalysis(reportId:string,doctorId:string){const report=await verify(reportId,doctorId);const key=process.env.GEMINI_API_KEY;if(!key)throw new Error("GEMINI_API_KEY is required for report analysis.");const model=process.env.GEMINI_MODEL||"gemini-2.5-flash";const [buffer]=await getAdminStorageBucket().file(report.storagePath!).download();if(buffer.length>12*1024*1024)throw new Error("Report is too large for inline analysis.");const prompt=`You are a document-organization assistant inside a clinician workspace. Analyze ONLY what is visibly/documentarily present in this report. Produce a concise summary and list explicit observations such as named tests, dates, values, sections, or statements. Do not diagnose, interpret clinical significance, recommend treatment, infer risk, or state that a finding is normal/abnormal unless the document itself explicitly labels it that way. documentedChanges must contain only explicit comparisons or changes stated in the document; otherwise return an empty array. limitations must state what the document does not establish. Doctor review is mandatory. Report metadata: ${JSON.stringify({title:report.title,reportType:report.reportType,uploadedAt:report.uploadedAt})}`;const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt},{inlineData:{mimeType:guessMime(report.fileName),data:buffer.toString("base64")}}]}],generationConfig:{responseMimeType:"application/json",responseSchema:schema()}})});if(!response.ok)throw new Error("Gemini report analysis failed: "+response.status);const body=await response.json();const raw=body?.candidates?.[0]?.content?.parts?.[0]?.text;if(typeof raw!=="string")throw new Error("AI returned no report analysis.");const parsed=JSON.parse(raw) as Omit<ReportAnalysis,"analysisId"|"reportId"|"patientId"|"doctorId"|"generatedAt"|"model"|"reviewStatus">;if(!parsed.summary||!Array.isArray(parsed.observations)||!Array.isArray(parsed.documentedChanges)||!Array.isArray(parsed.limitations))throw new Error("AI report analysis failed validation.");const analysis:ReportAnalysis={analysisId:crypto.randomUUID(),reportId,patientId:report.patientId,doctorId,generatedAt:new Date().toISOString(),model,summary:parsed.summary,observations:parsed.observations,documentedChanges:parsed.documentedChanges,limitations:parsed.limitations,reviewStatus:"pending-review"};await createDocument("reportAnalyses",analysis);return analysis;}
function guessMime(fileName:string){const n=fileName.toLowerCase();if(n.endsWith(".pdf"))return "application/pdf";if(n.endsWith(".png"))return "image/png";if(n.endsWith(".jpg")||n.endsWith(".jpeg"))return "image/jpeg";return "application/pdf";}
export async function listReportAnalyses(reportId:string,doctorId:string){await verify(reportId,doctorId);return listDocumentsByField<ReportAnalysis>("reportAnalyses","reportId",reportId).then(xs=>xs.filter(x=>x.doctorId===doctorId).sort((a,b)=>new Date(b.generatedAt).getTime()-new Date(a.generatedAt).getTime()));}
export async function reviewReportAnalysis(reportId:string,doctorId:string,analysisId:string,status:"reviewed"|"dismissed",reviewNote?:string){await verify(reportId,doctorId);const a=await getDocument<ReportAnalysis>("reportAnalyses",analysisId);if(!a||a.reportId!==reportId||a.doctorId!==doctorId)throw new Error("Analysis not found.");const next={...a,reviewStatus:status,reviewNote:reviewNote?.trim()||undefined};await setDocument("reportAnalyses",analysisId,next);return next;}
