function AIWorkspaceLinks({patientId}:{patientId:string}){return <section className="doctor-card"><span className="doctor-eyebrow">AI PATIENT 360</span><h2>AI-assisted care workspace</h2><p className="doctor-muted-text">Review AI summaries, engagement signals and evidence before making any care-team decision.</p><div><a href={"/doctor/signals?patientId="+encodeURIComponent(patientId)}>Engagement signals</a>{" · "}<a href={"/doctor/reference"}>Medical reference</a>{" · "}<a href={"/api/doctor/ai/care-journey-summary?patientId="+encodeURIComponent(patientId)} target="_blank" rel="noreferrer">Care journey summary</a></div></section>}
"use client";
import { useEffect,useMemo,useState } from "react";
import type { Patient } from "@/types/patient";
import type { Milestone } from "@/types/milestone";
import { auth } from "@/lib/firebase/client";
import { fetchDoctorPatient360 } from "@/lib/api/doctorPatient";
import { createDoctorMilestone, updateDoctorMilestone } from "@/lib/api/doctorMilestone";
import { replyToDoctorQuery, updateDoctorQueryStatus } from "@/lib/api/doctorQuery";
import type { QueryStatus } from "@/types/query";
import type { Medicine } from "@/types/medicine";
import type { Procedure } from "@/types/procedure";
import { createDoctorMedicine, updateDoctorMedicine } from "@/lib/api/doctorMedicine";
import { createDoctorProcedure, updateDoctorProcedure } from "@/lib/api/doctorProcedure";
import { updateDoctorCarePhase } from "@/lib/api/doctorCarePhase";
import { fetchDoctorCaregivers, createDoctorCaregiver, updateDoctorCaregiver } from "@/lib/api/doctorCaregiver";
import type { Caregiver, CaregiverAccessStatus } from "@/types/caregiver";
import { reviewDoctorReport } from "@/lib/api/doctorReport";
import DoctorPatientAIInsights from "./DoctorPatientAIInsights";\nimport DoctorMedicalReference from "./DoctorMedicalReference";
export default function DoctorPatient360({patientId,onBack}:{patientId:string;onBack:()=>void}) {
 const [data,setData]=useState<Awaited<ReturnType<typeof fetchDoctorPatient360>>|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;const unsub=auth.onIdTokenChanged(async user=>{if(!user){if(active){setError("Sign in with a doctor account to view patient history.");setLoading(false)}return}try{setLoading(true);setError(null);const [d,c]=await Promise.all([fetchDoctorPatient360(patientId),fetchDoctorCaregivers(patientId)]);if(active){setData(d);setCaregivers(c)}}catch(e){console.error(e);if(active)setError("Unable to load this patient history.")}finally{if(active)setLoading(false)}});return()=>{active=false;unsub()}},[patientId]);
 const phase=(p:Patient["currentCarePhase"])=>({"active-treatment":"Active Treatment","remission-survivorship":"Remission / Survivorship",relapse:"Relapse","transfer-of-care":"Transfer of Care","palliative-end-of-life":"Palliative / End-of-Life",deceased:"Deceased"}[p]);
 const date=(v?:string)=>{if(!v)return"Not recorded";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(d)};
 const [newTitle,setNewTitle]=useState(""); const [newDueDate,setNewDueDate]=useState(""); const [newDescription,setNewDescription]=useState(""); const [saving,setSaving]=useState(false);
 const [milestoneError,setMilestoneError]=useState<string|null>(null); const [reportNotes,setReportNotes]=useState<Record<string,string>>({}); const [reportError,setReportError]=useState<string|null>(null); const [reviewingReport,setReviewingReport]=useState<string|null>(null); const [caregivers,setCaregivers]=useState<Caregiver[]>([]); const [caregiverName,setCaregiverName]=useState(""); const [caregiverRelationship,setCaregiverRelationship]=useState(""); const [caregiverContact,setCaregiverContact]=useState(""); const [caregiverError,setCaregiverError]=useState<string|null>(null); const [phaseError,setPhaseError]=useState<string|null>(null); const [treatmentError,setTreatmentError]=useState<string|null>(null); const [medicineName,setMedicineName]=useState(""); const [medicineDosage,setMedicineDosage]=useState(""); const [medicineFrequency,setMedicineFrequency]=useState(""); const [medicineInstructions,setMedicineInstructions]=useState(""); const [medicineStart,setMedicineStart]=useState(""); const [procedureName,setProcedureName]=useState(""); const [procedureDate,setProcedureDate]=useState(""); const [procedurePurpose,setProcedurePurpose]=useState(""); const [procedureDetails,setProcedureDetails]=useState(""); const [reply,setReply]=useState(""); const [replying,setReplying]=useState<string|null>(null); const [queryError,setQueryError]=useState<string|null>(null);
 const events=useMemo(()=>data?[...data.appointments.map(x=>({d:x.date,t:x.title,s:`Appointment · ${x.status}`})),...data.procedures.map(x=>({d:x.date,t:x.name,s:`Procedure · ${x.status}`})),...data.reports.map(x=>({d:x.uploadedAt,t:x.title,s:`Report · ${x.status}`})),...data.milestones.map(x=>({d:x.completedAt??x.dueDate,t:x.title,s:`Milestone · ${x.status}`})),...data.queries.map(x=>({d:x.updatedAt,t:x.subject,s:`Query · ${x.status}`})),...data.medicines.map(x=>({d:x.startDate,t:x.name,s:`Medicine · ${x.status}`}))].sort((a,b)=>new Date(b.d).getTime()-new Date(a.d).getTime()):[],[data]);
 if(loading)return <section className="doctor-page"><div className="doctor-card doctor-directory-state">Loading patient 360°…</div></section>;
 if(error||!data)return <section className="doctor-page"><div className="doctor-card doctor-directory-state doctor-directory-error">{error??"Patient not found."}<button className="doctor-back-button" onClick={onBack}>Back to patients</button></div></section>;
 const {patient,appointments,medicines,procedures,reports,queries,milestones}=data;

 const refresh=async()=>{const [d,c]=await Promise.all([fetchDoctorPatient360(patientId),fetchDoctorCaregivers(patientId)]);setData(d);setCaregivers(c)};
 const inviteCaregiver=async()=>{if(!caregiverName.trim()||!caregiverRelationship.trim())return;try{setCaregiverError(null);await createDoctorCaregiver({patientId:patient.patientId,name:caregiverName.trim(),relationship:caregiverRelationship.trim(),contact:caregiverContact.trim()||undefined,permissions:["care-journey"]});setCaregiverName("");setCaregiverRelationship("");setCaregiverContact("");await refresh()}catch(e){console.error(e);setCaregiverError("Unable to invite caregiver.")}};
 const setCaregiverStatus=async(caregiverId:string,accessStatus:CaregiverAccessStatus)=>{try{setCaregiverError(null);await updateDoctorCaregiver({caregiverId,accessStatus});await refresh()}catch(e){console.error(e);setCaregiverError("Unable to update caregiver access.")}};
 const addMilestone=async()=>{if(!newTitle.trim()||!newDueDate)return;try{setSaving(true);setMilestoneError(null);await createDoctorMilestone({patientId,title:newTitle,description:newDescription,dueDate:newDueDate});setNewTitle("");setNewDueDate("");setNewDescription("");await refresh()}catch(e){console.error(e);setMilestoneError("Unable to save milestone.")}finally{setSaving(false)}};
 const setMilestoneStatus=async(milestoneId:string,status:Milestone["status"])=>{try{setMilestoneError(null);await updateDoctorMilestone({milestoneId,status});await refresh()}catch(e){console.error(e);setMilestoneError("Unable to update milestone.")}};
 const setCarePhase=async(currentCarePhase:Patient["currentCarePhase"])=>{try{setPhaseError(null);await updateDoctorCarePhase(patient.patientId,currentCarePhase);await refresh()}catch(e){console.error(e);setPhaseError("Unable to update care phase.")}};
 const sendReply=async(queryId:string)=>{if(!reply.trim())return;try{setReplying(queryId);setQueryError(null);await replyToDoctorQuery({queryId,message:reply});setReply("");await refresh()}catch(e){console.error(e);setQueryError("Unable to send reply.")}finally{setReplying(null)}};
 const setQueryStatus=async(queryId:string,status:QueryStatus)=>{try{setQueryError(null);await updateDoctorQueryStatus({queryId,status});await refresh()}catch(e){console.error(e);setQueryError("Unable to update query.")}};
 const addMedicine=async()=>{if(!medicineName.trim()||!medicineDosage.trim()||!medicineFrequency.trim()||!medicineInstructions.trim()||!medicineStart)return;try{setTreatmentError(null);await createDoctorMedicine({patientId:patient.patientId,name:medicineName.trim(),dosage:medicineDosage.trim(),frequency:medicineFrequency.trim(),instructions:medicineInstructions.trim(),sideEffects:[],startDate:medicineStart,status:"active"});setMedicineName("");setMedicineDosage("");setMedicineFrequency("");setMedicineInstructions("");setMedicineStart("");await refresh()}catch(e){console.error(e);setTreatmentError("Unable to save medicine.")}};
 const addProcedure=async()=>{if(!procedureName.trim()||!procedureDate)return;try{setTreatmentError(null);await createDoctorProcedure({patientId:patient.patientId,name:procedureName.trim(),date:procedureDate,purpose:procedurePurpose.trim()||undefined,details:procedureDetails.trim()||undefined,status:"scheduled"});setProcedureName("");setProcedureDate("");setProcedurePurpose("");setProcedureDetails("");await refresh()}catch(e){console.error(e);setTreatmentError("Unable to save procedure.")}};
 const setMedicineStatus=async(id:string,status:Medicine["status"])=>{try{await updateDoctorMedicine({medicineId:id,status});await refresh()}catch(e){console.error(e);setTreatmentError("Unable to update medicine.")}};
 const setProcedureStatus=async(id:string,status:Procedure["status"])=>{try{await updateDoctorProcedure({procedureId:id,status});await refresh()}catch(e){console.error(e);setTreatmentError("Unable to update procedure.")}};
 const reviewReport=async(reportId:string)=>{try{setReviewingReport(reportId);setReportError(null);await reviewDoctorReport({reportId,notes:reportNotes[reportId]});await refresh()}catch(e){console.error(e);setReportError("Unable to save report review.")}finally{setReviewingReport(null)}};
 return <section className="doctor-page"><button className="doctor-back-button" onClick={onBack}>← Patient Management</button>
 <div className="doctor-card doctor-360-header"><div><span className="doctor-eyebrow">Patient 360°</span><h2>{patient.name}</h2><p>{patient.patientId}{patient.age?` · Age ${patient.age}`:""}{patient.diagnosisLabel?` · ${patient.diagnosisLabel}`:""}</p></div><div className="doctor-360-phase"><span>Clinician-defined care phase</span><strong>{phase(patient.currentCarePhase)}</strong><select value={patient.currentCarePhase} onChange={e=>setCarePhase(e.target.value as Patient["currentCarePhase"])}><option value="active-treatment">Active Treatment</option><option value="remission-survivorship">Remission / Survivorship</option><option value="relapse">Relapse</option><option value="transfer-of-care">Transfer of Care</option><option value="palliative-end-of-life">Palliative / End-of-Life</option><option value="deceased">Deceased</option></select>{phaseError&&<small className="doctor-directory-error">{phaseError}</small>}</div></div>
 <div className="doctor-360-grid"><article className="doctor-card"><span className="doctor-eyebrow">Journey</span><h2>Care journey progress</h2><div className="doctor-journey-progress"><div><span style={{width:`${Math.max(0,Math.min(100,patient.journeyProgress))}%`}}/></div><strong>{patient.journeyProgress}%</strong></div><p className="doctor-muted-text">{milestones.length} milestones · Last updated {date(patient.lastUpdatedAt)}</p></article><article className="doctor-card"><span className="doctor-eyebrow">At a glance</span><h2>Record counts</h2><div className="doctor-count-grid">{[["Appointments",appointments.length],["Medicines",medicines.length],["Procedures",procedures.length],["Reports",reports.length],["Queries",queries.length],["Milestones",milestones.length]].map(([n,v])=><span key={String(n)}><strong>{v}</strong>{n}</span>)}</div></article></div>
 <DoctorPatientAIInsights patientId={patient.patientId}/><DoctorMedicalReference/><article className="doctor-card"><span className="doctor-eyebrow">Caregiver access</span><h2>Consent-controlled caregiver coordination</h2>{caregiverError&&<p className="doctor-directory-error">{caregiverError}</p>}<div className="doctor-treatment-form"><input value={caregiverName} onChange={e=>setCaregiverName(e.target.value)} placeholder="Caregiver name"/><input value={caregiverRelationship} onChange={e=>setCaregiverRelationship(e.target.value)} placeholder="Relationship"/><input value={caregiverContact} onChange={e=>setCaregiverContact(e.target.value)} placeholder="Contact (optional)"/><button onClick={inviteCaregiver} disabled={!caregiverName.trim()||!caregiverRelationship.trim()}>Invite caregiver</button></div>{caregivers.length?caregivers.map(c=><div className="doctor-mini-row" key={c.caregiverId}><div><strong>{c.name}</strong><span>{c.relationship}{c.contact?` · ${c.contact}`:""} · {c.permissions.join(", ")||"No permissions"}</span></div><select value={c.accessStatus} onChange={e=>setCaregiverStatus(c.caregiverId,e.target.value as CaregiverAccessStatus)}><option value="invited">Invited</option><option value="consented">Consented</option><option value="active">Active</option><option value="revoked">Revoked</option></select></div>):<p className="doctor-muted-text">No caregiver access records.</p>}</article><article className="doctor-card"><span className="doctor-eyebrow">Care plan</span><h2>Manage milestones</h2><div className="doctor-milestone-form"><input value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Milestone title"/><input type="date" value={newDueDate} onChange={e=>setNewDueDate(e.target.value)}/><input value={newDescription} onChange={e=>setNewDescription(e.target.value)} placeholder="Description (optional)"/><button onClick={addMilestone} disabled={saving||!newTitle.trim()||!newDueDate}>{saving?"Saving…":"Add milestone"}</button></div>{milestoneError&&<p className="doctor-directory-error">{milestoneError}</p>}<div className="doctor-milestone-list">{milestones.map(m=><div className="doctor-milestone-row" key={m.milestoneId}><div><strong>{m.title}</strong><span>{m.description??"No description"} · Due {date(m.dueDate)}</span></div><select value={m.status} onChange={e=>setMilestoneStatus(m.milestoneId,e.target.value as Milestone["status"])}><option value="pending">Pending</option><option value="completed">Completed</option><option value="overdue">Overdue</option><option value="cancelled">Cancelled</option></select></div>)}</div></article>
 <div className="doctor-360-grid"><article className="doctor-card"><span className="doctor-eyebrow">Care history</span><h2>Longitudinal timeline</h2><div className="doctor-timeline">{events.length?events.map((e,i)=><div className="doctor-timeline-item" key={e.t+e.d+i}><div className="doctor-timeline-dot"/><time>{date(e.d)}</time><strong>{e.t}</strong><span>{e.s}</span></div>):<p className="doctor-muted-text">No timeline events are available.</p>}</div></article><div className="doctor-360-stack"><article className="doctor-card"><span className="doctor-eyebrow">Appointments</span><h2>Recent / upcoming</h2>{appointments.slice(0,4).map(x=><div className="doctor-mini-row" key={x.appointmentId}><div><strong>{x.title}</strong><span>{date(x.date)} · {x.time}</span></div><em>{x.status}</em></div>)}</article><article className="doctor-card"><span className="doctor-eyebrow">Medicines</span><h2>Assigned medicines</h2>{medicines.slice(0,4).map(x=><div className="doctor-mini-row" key={x.medicineId}><div><strong>{x.name}</strong><span>{x.dosage} · {x.frequency}</span></div><em>{x.status}</em></div>)}</article></div></div>
 <article className="doctor-card"><span className="doctor-eyebrow">Treatment management</span><h2>Medicines & procedures</h2>{treatmentError&&<p className="doctor-directory-error">{treatmentError}</p>}<div className="doctor-treatment-form"><input value={medicineName} onChange={e=>setMedicineName(e.target.value)} placeholder="Medicine name"/><input value={medicineDosage} onChange={e=>setMedicineDosage(e.target.value)} placeholder="Dosage"/><input value={medicineFrequency} onChange={e=>setMedicineFrequency(e.target.value)} placeholder="Frequency"/><input value={medicineInstructions} onChange={e=>setMedicineInstructions(e.target.value)} placeholder="Instructions"/><input type="date" value={medicineStart} onChange={e=>setMedicineStart(e.target.value)}/><button onClick={addMedicine}>Add medicine</button></div><div className="doctor-treatment-form"><input value={procedureName} onChange={e=>setProcedureName(e.target.value)} placeholder="Procedure name"/><input type="date" value={procedureDate} onChange={e=>setProcedureDate(e.target.value)}/><input value={procedurePurpose} onChange={e=>setProcedurePurpose(e.target.value)} placeholder="Purpose (optional)"/><input value={procedureDetails} onChange={e=>setProcedureDetails(e.target.value)} placeholder="Details (optional)"/><button onClick={addProcedure}>Add procedure</button></div><div className="doctor-treatment-list">{medicines.map(x=><div className="doctor-mini-row" key={x.medicineId}><div><strong>{x.name}</strong><span>{x.dosage} · {x.frequency} · {x.instructions}</span></div><select value={x.status} onChange={e=>setMedicineStatus(x.medicineId,e.target.value as Medicine["status"])}><option value="active">Active</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div>)}{procedures.map(x=><div className="doctor-mini-row" key={x.procedureId}><div><strong>{x.name}</strong><span>{date(x.date)} · {x.purpose??"No purpose recorded"}</span></div><select value={x.status} onChange={e=>setProcedureStatus(x.procedureId,e.target.value as Procedure["status"])}><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div>)}</div></article>
 <div className="doctor-360-grid"><article className="doctor-card"><span className="doctor-eyebrow">Procedures</span><h2>Procedure history</h2>{procedures.map(x=><div className="doctor-detail-row" key={x.procedureId}><strong>{x.name}</strong><span>{date(x.date)} · {x.status}</span>{x.purpose&&<p>{x.purpose}</p>}</div>)}</article><article className="doctor-card"><span className="doctor-eyebrow">Reports</span><h2>Report review</h2>{reportError&&<p className="doctor-directory-error">{reportError}</p>}{reports.map(x=><div className="doctor-detail-row" key={x.reportId}><strong>{x.title}</strong><span>{x.reportType??"Report"} · {date(x.uploadedAt)} · {x.status}</span>{x.notes&&<p>Review note: {x.notes}</p>}<input value={reportNotes[x.reportId]??""} onChange={e=>setReportNotes(v=>({...v,[x.reportId]:e.target.value}))} placeholder="Doctor review note (optional)"/><button onClick={()=>reviewReport(x.reportId)} disabled={reviewingReport===x.reportId}>{reviewingReport===x.reportId?"Saving…":x.status==="reviewed"?"Update review":"Mark reviewed"}</button></div>)}</article></div>
 <article className="doctor-card"><span className="doctor-eyebrow">Patient communication</span><h2>Queries</h2>{queryError&&<p className="doctor-directory-error">{queryError}</p>}{queries.length?queries.map(x=><div className="doctor-detail-row doctor-query-card" key={x.queryId}><div className="doctor-query-heading"><strong>{x.subject}</strong><select value={x.status} onChange={e=>setQueryStatus(x.queryId,e.target.value as QueryStatus)}><option value="open">Open</option><option value="answered">Answered</option><option value="resolved">Resolved</option></select></div><span>{x.status} · Updated {date(x.updatedAt)}</span><div className="doctor-query-messages">{x.messages.map(m=><p key={m.messageId}><strong>{m.senderRole==="patient"?"Patient":"Doctor"}:</strong> {m.message}</p>)}</div><div className="doctor-query-reply"><input value={replying===x.queryId?reply:""} onChange={e=>{setReply(e.target.value);setReplying(x.queryId)}} onFocus={()=>setReplying(x.queryId)} placeholder="Reply to patient…"/><button onClick={()=>sendReply(x.queryId)} disabled={replying===x.queryId?(!reply.trim()):false}>Send</button></div></div>):<p className="doctor-muted-text">No patient queries.</p>}</article></section>;
}
