"use client";
import {useEffect,useState} from "react";
import {auth} from "@/lib/firebase/client";
import {fetchDoctorOverview, type DoctorOverview} from "@/lib/api/doctorOverview";
import {fetchDoctorSignals,reviewDoctorSignal} from "@/lib/api/doctorSignals";
import type {EngagementSignal} from "@/types/engagementSignal";import DoctorAttentionQueue from "./DoctorAttentionQueue";
export default function DoctorOverviewFoundation(){
 const [data,setData]=useState<DoctorOverview|null>(null);const [signals,setSignals]=useState<EngagementSignal[]>([]);const [error,setError]=useState<string|null>(null);const [reviewNote,setReviewNote]=useState<Record<string,string>>({});const [reviewing,setReviewing]=useState<string|null>(null);
 useEffect(()=>{let active=true;const u=auth.onIdTokenChanged(async user=>{if(!user){setError("Sign in with a doctor account to view the command center.");return}try{const [d,s]=await Promise.all([fetchDoctorOverview(),fetchDoctorSignals()]);if(active){setData(d);setSignals(s)}}catch(e){console.error(e);if(active)setError("Unable to load command center data.")}});return()=>{active=false;u()}},[]);
 const review=async(signalId:string,status:"reviewed"|"dismissed")=>{try{setReviewing(signalId);await reviewDoctorSignal({signalId,status,note:reviewNote[signalId]});setSignals(await fetchDoctorSignals())}catch(e){console.error(e);setError("Unable to update signal review.")}finally{setReviewing(null)}};
 if(error)return <section className="doctor-page"><div className="doctor-card doctor-directory-state doctor-directory-error">{error}</div></section>;
 const cards=data?[["Total patients",data.totalPatients,"Assigned patient cohort"],["Active patients",data.activePatients,"Patients not marked deceased"],["Today appointments",data.todayAppointments,"Scheduled for today"],["Pending queries",data.pendingQueries,"Open patient conversations"],["Reports to review",data.reportsForReview,"Uploaded reports awaiting review"],["Upcoming follow-ups",data.upcomingFollowUps,"Scheduled appointments from today"]]:[];
 return <section className="doctor-page"><div className="doctor-welcome-card"><div><span className="doctor-eyebrow">Care-team command center</span><h2>Longitudinal care operations at a glance.</h2><p>Live counts are scoped to patients assigned to your authenticated doctor account.</p></div><div className="doctor-flow-badge">Shared patient data</div></div><div className="doctor-metric-grid">{cards.map(([label,value,detail])=><article className="doctor-card doctor-metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div><div className="doctor-content-grid"><article className="doctor-card"><div className="doctor-card-heading"><div><span className="doctor-eyebrow">Human review</span><h2>Engagement signals</h2></div><span className="doctor-neutral-pill">{signals.length} pending</span></div>{signals.length?signals.map((s,i)=><div className="doctor-review-item" key={s.signalId}><div className="doctor-review-number">{i+1}</div><div><strong>{s.title}</strong><p>{s.description}</p><small>Signal only · requires clinician review</small><div className="doctor-signal-actions"><input value={reviewNote[s.signalId]??""} onChange={e=>setReviewNote({...reviewNote,[s.signalId]:e.target.value})} placeholder="Review note (optional)"/><button disabled={reviewing===s.signalId} onClick={()=>review(s.signalId,"reviewed")}>Review</button><button disabled={reviewing===s.signalId} onClick={()=>review(s.signalId,"dismissed")}>Dismiss</button></div></div></div>):<p className="doctor-muted-text">No engagement signals require review.</p>}</article><article className="doctor-card"><div className="doctor-card-heading"><div><span className="doctor-eyebrow">Recent activity</span><h2>Patient activity</h2></div><span className="doctor-neutral-pill">Live data</span></div>{data?.recentActivity.length?data.recentActivity.map((x,i)=><div className="doctor-review-item" key={x.title+x.date+i}><div className="doctor-review-number">{i+1}</div><div><strong>{x.title}</strong><p>{x.detail}</p></div></div>):<p className="doctor-muted-text">No recent activity is available.</p>}</article><article className="doctor-card doctor-ai-card"><span className="doctor-eyebrow">AI workflow</span><h2>AI supports review, not clinical decisions.</h2><div className="doctor-ai-flow"><span>Patient data</span><b>→</b><span>Neural AI</span><b>→</b><span>Evidence / signal</span><b>→</b><span>Doctor review</span></div><p>Clinical decisions remain with the care team. This command center only surfaces operational data and review queues.</p></article></div><DoctorAttentionQueue /></section>;
}