"use client";
import {useEffect,useMemo,useState} from "react";
import type {Patient} from "@/types/patient";import type {Appointment} from "@/types/appointment";import type {DoctorNote} from "@/types/doctorNote";
import {authenticatedFetch} from "@/lib/api/authenticatedFetch";import {createDoctorAppointment,updateDoctorAppointment} from "@/lib/api/doctorAppointments";import {createDoctorNote,fetchDoctorNotes} from "@/lib/api/doctorNotes";
type Row=Record<string,any>;type Data={patients:Patient[];appointments:Appointment[];medicines:Row[];procedures:Row[];reports:Row[];queries:Row[];milestones:Row[];caregivers:Row[];sosEvents:Row[];auditLogs:Row[]};
function date(v?:string){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(d);}
function name(ps:Patient[],id:string){return ps.find(p=>p.patientId===id)?.name??id;}
function Table({children,headers}:{children:React.ReactNode;headers:string[]}){return <div className="doctor-workspace-table-wrap"><table className="doctor-workspace-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export default function DoctorOperationsWorkspace({mode}:{mode:"progress"|"appointments"|"care-plans"|"notes"}){
 const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[patientId,setPatientId]=useState("");const[notes,setNotes]=useState<DoctorNote[]>([]);
 const[form,setForm]=useState({title:"",date:"",time:"",location:"",instructions:""});const[noteForm,setNoteForm]=useState({patientId:"",title:"",content:""});
 async function load(){try{setLoading(true);const r=await authenticatedFetch("/api/doctor/workspace");if(!r.ok)throw new Error("Workspace request failed.");const d=(await r.json()).data as Data;setData(d);if(mode==="notes")setNotes(await fetchDoctorNotes());}catch(e){setError(e instanceof Error?e.message:"Unable to load workspace.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[mode]);
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date());
 const progress=useMemo(()=>{if(!data)return[];return data.patients.map(p=>{const ms=data.milestones.filter(x=>x.patientId===p.patientId&&x.status!=="cancelled");const done=ms.filter(x=>x.status==="completed").length;const ap=data.appointments.filter(x=>x.patientId===p.patientId);const missed=ap.filter(x=>x.status==="missed").length;const openQ=data.queries.filter(x=>x.patientId===p.patientId&&x.status==="open").length;return {...p,milestones:ms.length,completed:done,missedAppointments:missed,openQueries:openQ,calculatedProgress:ms.length?Math.round(done/ms.length*100):p.journeyProgress}})},[data]);
 const appts=useMemo(()=>data?.appointments.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))??[],[data]);
 async function schedule(e:React.FormEvent){e.preventDefault();if(!patientId||!form.title||!form.date||!form.time)return;try{await createDoctorAppointment({patientId,doctorId:data?.appointments[0]?.doctorId??"",...form,status:"scheduled"});setForm({title:"",date:"",time:"",location:"",instructions:""});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to schedule appointment.")}}
 async function updateAppointment(a:Appointment,status:Appointment["status"]){try{await updateDoctorAppointment({appointmentId:a.appointmentId,status});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update appointment.")}}
 async function saveNote(e:React.FormEvent){e.preventDefault();if(!noteForm.patientId||!noteForm.title||!noteForm.content)return;try{await createDoctorNote(noteForm);setNoteForm({patientId:"",title:"",content:""});setNotes(await fetchDoctorNotes())}catch(e){setError(e instanceof Error?e.message:"Unable to save note.")}}
 if(loading)return <main className="doctor-page"><div className="doctor-card doctor-directory-state">Loading {mode}…</div></main>;
 if(error&&!data)return <main className="doctor-page"><div className="doctor-card doctor-directory-state doctor-directory-error">{error}</div></main>;
 if(mode==="progress")return <main className="doctor-page"><div className="doctor-card"><span className="doctor-eyebrow">PATIENT PROGRESS</span><h1>Progress & follow-up</h1><p className="doctor-muted-text">Cohort-level progress derived from the same milestones, appointments and queries visible in Patient 360.</p></div><div className="doctor-metric-grid"><article className="doctor-card doctor-metric-card"><span>Patients</span><strong>{progress.length}</strong></article><article className="doctor-card doctor-metric-card"><span>Open queries</span><strong>{progress.reduce((n,x)=>n+x.openQueries,0)}</strong></article><article className="doctor-card doctor-metric-card"><span>Missed appointments</span><strong>{progress.reduce((n,x)=>n+x.missedAppointments,0)}</strong></article><article className="doctor-card doctor-metric-card"><span>Milestones complete</span><strong>{progress.reduce((n,x)=>n+x.completed,0)}</strong></article></div><section className="doctor-card"><Table headers={["Patient","Phase","Journey","Milestones","Missed visits","Open queries","Updated"]}>{progress.map(p=><tr key={p.patientId}><td><strong>{p.name}</strong><span>{p.patientId}</span></td><td>{p.currentCarePhase}</td><td>{p.calculatedProgress}%</td><td>{p.completed}/{p.milestones}</td><td>{p.missedAppointments}</td><td>{p.openQueries}</td><td>{date(p.lastUpdatedAt)}</td></tr>)}</Table></section></main>;
 if(mode==="appointments")return <main className="doctor-page"><section className="doctor-card"><span className="doctor-eyebrow">APPOINTMENTS</span><h1>Appointments & follow-ups</h1><p className="doctor-muted-text">Scheduling writes to the same appointments collection consumed by the patient portal.</p><form className="doctor-treatment-form" onSubmit={schedule}><select value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Select patient</option>{data?.patients.map(p=><option key={p.patientId} value={p.patientId}>{p.name}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Appointment title"/><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Location"/><input value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})} placeholder="Instructions"/><button type="submit">Schedule</button></form></section><section className="doctor-card"><Table headers={["Patient","Appointment","When","Status","Action"]}>{appts.map(a=><tr key={a.appointmentId}><td>{name(data!.patients,a.patientId)}</td><td><strong>{a.title}</strong><span>{a.location??"Location not recorded"}</span></td><td>{a.date} · {a.time}</td><td>{a.status}</td><td><select value={a.status} onChange={e=>void updateAppointment(a,e.target.value as Appointment["status"])}><option value="scheduled">scheduled</option><option value="completed">completed</option><option value="missed">missed</option><option value="cancelled">cancelled</option></select></td></tr>)}</Table></section></main>;
 if(mode==="care-plans")return <main className="doctor-page"><section className="doctor-card"><span className="doctor-eyebrow">CARE PLANS</span><h1>Care plan operations</h1><p className="doctor-muted-text">Milestones, medicines and procedures are shown from the same records that the patient portal displays. Open Patient 360° to edit the existing clinical records.</p></section><section className="doctor-card"><Table headers={["Patient","Type","Item","Detail","Date","Status"]}>{[...(data?.milestones??[]).map(x=>({type:"Milestone",patientId:x.patientId,item:x.title,detail:x.description??"—",date:x.dueDate,status:x.status})),...(data?.medicines??[]).map(x=>({type:"Medicine",patientId:x.patientId,item:x.name,detail:x.dosage+" · "+x.frequency,date:x.startDate,status:x.status})),...(data?.procedures??[]).map(x=>({type:"Procedure",patientId:x.patientId,item:x.name,detail:x.purpose??x.details??"—",date:x.date,status:x.status}))].map((x,i)=><tr key={x.type+x.item+i}><td>{name(data!.patients,x.patientId)}</td><td>{x.type}</td><td><strong>{x.item}</strong></td><td>{x.detail}</td><td>{date(x.date)}</td><td>{x.status}</td></tr>)}</Table></section></main>;
 return <main className="doctor-page"><section className="doctor-card"><span className="doctor-eyebrow">PRIVATE CLINICAL NOTES</span><h1>Doctor notes</h1><p className="doctor-muted-text">Private notes are stored separately from patient-visible records and never appear in the patient portal.</p><form className="doctor-treatment-form" onSubmit={saveNote}><select value={noteForm.patientId} onChange={e=>setNoteForm({...noteForm,patientId:e.target.value})}><option value="">Select patient</option>{data?.patients.map(p=><option key={p.patientId} value={p.patientId}>{p.name}</option>)}</select><input value={noteForm.title} onChange={e=>setNoteForm({...noteForm,title:e.target.value})} placeholder="Note title"/><textarea value={noteForm.content} onChange={e=>setNoteForm({...noteForm,content:e.target.value})} placeholder="Private clinical note" rows={5}/><button type="submit">Save private note</button></form></section><section className="doctor-card">{notes.map(n=><article className="doctor-detail-row" key={n.noteId}><strong>{n.title}</strong><span>{name(data!.patients,n.patientId)} · Updated {date(n.updatedAt)}</span><p>{n.content}</p></article>)}</section></main>;
}