"use client";
import { useEffect,useMemo,useState } from "react";
import type { Patient } from "@/types/patient";
import type { Milestone } from "@/types/milestone";
import { auth } from "@/lib/firebase/client";
import { fetchDoctorPatient360 } from "@/lib/api/doctorPatient";
import { createDoctorMilestone, updateDoctorMilestone } from "@/lib/api/doctorMilestone";
export default function DoctorPatient360({patientId,onBack}:{patientId:string;onBack:()=>void}) {
 const [data,setData]=useState<Awaited<ReturnType<typeof fetchDoctorPatient360>>|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;const unsub=auth.onIdTokenChanged(async user=>{if(!user){if(active){setError("Sign in with a doctor account to view patient history.");setLoading(false)}return}try{setLoading(true);setError(null);const d=await fetchDoctorPatient360(patientId);if(active)setData(d)}catch(e){console.error(e);if(active)setError("Unable to load this patient history.")}finally{if(active)setLoading(false)}});return()=>{active=false;unsub()}},[patientId]);
 const phase=(p:Patient["currentCarePhase"])=>({"active-treatment":"Active Treatment","remission-survivorship":"Remission / Survivorship",relapse:"Relapse","transfer-of-care":"Transfer of Care","palliative-end-of-life":"Palliative / End-of-Life",deceased:"Deceased"}[p]);
 const date=(v?:string)=>{if(!v)return"Not recorded";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(d)};
 const events=useMemo(()=>data?[...data.appointments.map(x=>({d:x.date,t:x.title,s:`Appointment · ${x.status}`})),...data.procedures.map(x=>({d:x.date,t:x.name,s:`Procedure · ${x.status}`})),...data.reports.map(x=>({d:x.uploadedAt,t:x.title,s:`Report · ${x.status}`})),...data.milestones.map(x=>({d:x.completedAt??x.dueDate,t:x.title,s:`Milestone · ${x.status}`})),...data.queries.map(x=>({d:x.updatedAt,t:x.subject,s:`Query · ${x.status}`})),...data.medicines.map(x=>({d:x.startDate,t:x.name,s:`Medicine · ${x.status}`}))].sort((a,b)=>new Date(b.d).getTime()-new Date(a.d).getTime()):[],[data]);
 if(loading)return <section className="doctor-page"><div className="doctor-card doctor-directory-state">Loading patient 360°…</div></section>;
 if(error||!data)return <section className="doctor-page"><div className="doctor-card doctor-directory-state doctor-directory-error">{error??"Patient not found."}<button className="doctor-back-button" onClick={onBack}>Back to patients</button></div></section>;
 const {patient,appointments,medicines,procedures,reports,queries,milestones}=data;
 const [newTitle,setNewTitle]=useState(""); const [newDueDate,setNewDueDate]=useState(""); const [newDescription,setNewDescription]=useState(""); const [saving,setSaving]=useState(false);
 const [milestoneError,setMilestoneError]=useState<string|null>(null);
 const refresh=async()=>{const d=await fetchDoctorPatient360(patientId);setData(d)};
 const addMilestone=async()=>{if(!newTitle.trim()||!newDueDate)return;try{setSaving(true);setMilestoneError(null);await createDoctorMilestone({patientId,title:newTitle,description:newDescription,dueDate:newDueDate});setNewTitle("");setNewDueDate("");setNewDescription("");await refresh()}catch(e){console.error(e);setMilestoneError("Unable to save milestone.")}finally{setSaving(false)}};
 const setMilestoneStatus=async(milestoneId:string,status:Milestone["status"])=>{try{setMilestoneError(null);await updateDoctorMilestone({milestoneId,status});await refresh()}catch(e){console.error(e);setMilestoneError("Unable to update milestone.")}};
 return <section className="doctor-page"><button className="doctor-back-button" onClick={onBack}>← Patient Management</button>
 <div className="doctor-card doctor-360-header"><div><span className="doctor-eyebrow">Patient 360°</span><h2>{patient.name}</h2><p>{patient.patientId}{patient.age?` · Age ${patient.age}`:""}{patient.diagnosisLabel?` · ${patient.diagnosisLabel}`:""}</p></div><div className="doctor-360-phase"><span>Clinician-defined care phase</span><strong>{phase(patient.currentCarePhase)}</strong></div></div>
 <div className="doctor-360-grid"><article className="doctor-card"><span className="doctor-eyebrow">Journey</span><h2>Care journey progress</h2><div className="doctor-journey-progress"><div><span style={{width:`${Math.max(0,Math.min(100,patient.journeyProgress))}%`}}/></div><strong>{patient.journeyProgress}%</strong></div><p className="doctor-muted-text">{milestones.length} milestones · Last updated {date(patient.lastUpdatedAt)}</p></article><article className="doctor-card"><span className="doctor-eyebrow">At a glance</span><h2>Record counts</h2><div className="doctor-count-grid">{[["Appointments",appointments.length],["Medicines",medicines.length],["Procedures",procedures.length],["Reports",reports.length],["Queries",queries.length],["Milestones",milestones.length]].map(([n,v])=><span key={String(n)}><strong>{v}</strong>{n}</span>)}</div></article></div>
 <article className="doctor-card"><span className="doctor-eyebrow">Care plan</span><h2>Manage milestones</h2><div className="doctor-milestone-form"><input value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Milestone title"/><input type="date" value={newDueDate} onChange={e=>setNewDueDate(e.target.value)}/><input value={newDescription} onChange={e=>setNewDescription(e.target.value)} placeholder="Description (optional)"/><button onClick={addMilestone} disabled={saving||!newTitle.trim()||!newDueDate}>{saving?"Saving…":"Add milestone"}</button></div>{milestoneError&&<p className="doctor-directory-error">{milestoneError}</p>}<div className="doctor-milestone-list">{milestones.map(m=><div className="doctor-milestone-row" key={m.milestoneId}><div><strong>{m.title}</strong><span>{m.description??"No description"} · Due {date(m.dueDate)}</span></div><select value={m.status} onChange={e=>setMilestoneStatus(m.milestoneId,e.target.value as Milestone["status"])}><option value="pending">Pending</option><option value="completed">Completed</option><option value="overdue">Overdue</option><option value="cancelled">Cancelled</option></select></div>)}</div></article>
 <div className="doctor-360-grid"><article className="doctor-card"><span className="doctor-eyebrow">Care history</span><h2>Longitudinal timeline</h2><div className="doctor-timeline">{events.length?events.map((e,i)=><div className="doctor-timeline-item" key={e.t+e.d+i}><div className="doctor-timeline-dot"/><time>{date(e.d)}</time><strong>{e.t}</strong><span>{e.s}</span></div>):<p className="doctor-muted-text">No timeline events are available.</p>}</div></article><div className="doctor-360-stack"><article className="doctor-card"><span className="doctor-eyebrow">Appointments</span><h2>Recent / upcoming</h2>{appointments.slice(0,4).map(x=><div className="doctor-mini-row" key={x.appointmentId}><div><strong>{x.title}</strong><span>{date(x.date)} · {x.time}</span></div><em>{x.status}</em></div>)}</article><article className="doctor-card"><span className="doctor-eyebrow">Medicines</span><h2>Assigned medicines</h2>{medicines.slice(0,4).map(x=><div className="doctor-mini-row" key={x.medicineId}><div><strong>{x.name}</strong><span>{x.dosage} · {x.frequency}</span></div><em>{x.status}</em></div>)}</article></div></div>
 <div className="doctor-360-grid"><article className="doctor-card"><span className="doctor-eyebrow">Procedures</span><h2>Procedure history</h2>{procedures.map(x=><div className="doctor-detail-row" key={x.procedureId}><strong>{x.name}</strong><span>{date(x.date)} · {x.status}</span>{x.purpose&&<p>{x.purpose}</p>}</div>)}</article><article className="doctor-card"><span className="doctor-eyebrow">Reports</span><h2>Report records</h2>{reports.map(x=><div className="doctor-detail-row" key={x.reportId}><strong>{x.title}</strong><span>{x.reportType??"Report"} · {date(x.uploadedAt)} · {x.status}</span>{x.notes&&<p>{x.notes}</p>}</div>)}</article></div>
 <article className="doctor-card"><span className="doctor-eyebrow">Patient communication</span><h2>Queries</h2>{queries.map(x=><div className="doctor-detail-row" key={x.queryId}><strong>{x.subject}</strong><span>{x.status} · Updated {date(x.updatedAt)}</span><p>{x.messages.at(-1)?.message??"No messages."}</p></div>)}</article></section>;
}
