"use client";
import {useEffect,useState} from "react";
import type {Notification} from "@/types/notification";
import {auth,db} from "@/lib/firebase/client";
import {collection,onSnapshot,query,where} from "firebase/firestore";
import {markPatientNotificationRead} from "@/lib/api/notifications";
export default function NotificationCenter(){const[items,setItems]=useState<Notification[]>([]);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
useEffect(()=>{let active=true;let unsubscribe=()=>{};const authUnsubscribe=auth.onIdTokenChanged(user=>{unsubscribe();if(!user){if(active){setItems([]);setLoading(false);setError("Please sign in.")}return;}void user.getIdTokenResult(true).then(token=>{const patientId=typeof token.claims.patientId==="string"?token.claims.patientId:null;if(!patientId){if(active){setLoading(false);setError("Your account is not linked to a patient record.")}return;}const q=query(collection(db,"notifications"),where("patientId","==",patientId));unsubscribe=onSnapshot(q,snapshot=>{if(!active)return;const next=snapshot.docs.map(d=>d.data() as Notification).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());setItems(next);setLoading(false);setError(null)},e=>{console.error("Realtime notification listener failed",e);if(active){setLoading(false);setError("Unable to sync notifications.")}})}).catch(e=>{console.error(e);if(active){setLoading(false);setError("Unable to initialize notifications.")}})});return()=>{active=false;unsubscribe();authUnsubscribe()}},[]);
const markRead=async(id:string)=>{try{const updated=await markPatientNotificationRead(id);setItems(v=>v.map(n=>n.notificationId===id?updated:n))}catch(e){setError(e instanceof Error?e.message:"Unable to update notification.")}};
const unread=items.filter(n=>n.status!=="read").length;
return <section className="patient-card"><div className="patient-card-heading"><div><span className="patient-eyebrow">NOTIFICATIONS</span><h2>Updates & reminders</h2></div><button onClick={()=>setOpen(v=>!v)}>{open?"Hide":"View"}{unread?" ("+unread+")":""}</button></div>{error&&<p className="patient-directory-error">{error}</p>}{open&&<div>{loading?<p>Loading notifications…</p>:items.length===0?<p>No notifications yet.</p>:items.map(n=><article key={n.notificationId} className="patient-notification"><div><strong>{n.title}</strong><p>{n.message}</p><small>{new Date(n.createdAt).toLocaleString()} · {n.channel} · {n.status}</small></div>{n.status!=="read"&&<button onClick={()=>markRead(n.notificationId)}>Mark as read</button>}</article>)}</div>}</section>}