"use client";
import {useEffect,useState} from "react";
import {askPatientCompanion,fetchPatientAIConversations,fetchPatientAIMessages} from "@/lib/api/patientAI";
import type {PatientAIConversation,PatientAIMessage} from "@/types/patientAIConversation";
type Message={role:"patient"|"ai";text:string;evidence?:string[];limitations?:string[]};
function toMessages(xs:PatientAIMessage[]):Message[]{return xs.map(x=>({role:x.role,text:x.text,evidence:x.evidence,limitations:x.limitations}));}
export default function PatientAICompanion(){
 const [conversations,setConversations]=useState<PatientAIConversation[]>([]),[activeId,setActiveId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[loading,setLoading]=useState(false),[historyLoading,setHistoryLoading]=useState(true),[error,setError]=useState<string|null>(null);
 useEffect(()=>{fetchPatientAIConversations().then(xs=>{setConversations(xs);if(xs[0])setActiveId(xs[0].conversationId)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load conversations.")).finally(()=>setHistoryLoading(false));},[]);
 useEffect(()=>{if(!activeId){setMessages([]);return;}setHistoryLoading(true);fetchPatientAIMessages(activeId).then(xs=>setMessages(toMessages(xs))).catch(e=>setError(e instanceof Error?e.message:"Unable to load conversation.")).finally(()=>setHistoryLoading(false));},[activeId]);
 async function send(){const q=draft.trim();if(!q||loading)return;setMessages(x=>[...x,{role:"patient",text:q}]);setDraft("");setError(null);setLoading(true);try{const r=await askPatientCompanion(q,activeId||undefined);setActiveId(r.conversationId);setMessages(x=>[...x,{role:"ai",text:r.output.answer,evidence:r.output.evidence,limitations:r.output.limitations}]);const xs=await fetchPatientAIConversations();setConversations(xs);}catch(e){setError(e instanceof Error?e.message:"Unable to contact the AI companion.");}finally{setLoading(false);}}
 function newChat(){setActiveId(null);setMessages([]);setError(null);}
 return <section className="patient-card ai-companion-card"><div className="patient-card-heading"><div><span className="patient-eyebrow">ONKO AI COMPANION</span><h1 className="onko-page-title">Your care-journey companion</h1><p className="onko-page-subtitle">Ask about information already recorded in your OnKo care journey, appointments, medicines, procedures, or milestones.</p></div><span className="ai-companion-badge">AI · CARE JOURNEY</span></div>
 <div className="ai-companion-notice"><strong>AI support, not clinical advice</strong><span>This companion does not diagnose, interpret reports, prescribe, or change treatment. For clinical decisions, contact your care team.</span></div>
 <div className="ai-companion-workspace"><aside className="ai-companion-history"><button type="button" onClick={newChat} className="ai-companion-new">+ New conversation</button>{historyLoading&&!conversations.length?<span className="patient-muted">Loading history…</span>:conversations.length?conversations.map(x=><button type="button" key={x.conversationId} onClick={()=>setActiveId(x.conversationId)} className={`ai-companion-history-item${activeId===x.conversationId?" active":""}`}>{x.title}</button>):<span className="patient-muted">No previous conversations.</span>}</aside>
 <div className="ai-companion-main"><div className="ai-companion-messages">{historyLoading&&activeId?<div className="ai-companion-empty"><span>Loading conversation…</span></div>:messages.length?messages.map((m,i)=><article key={i} className={`ai-companion-message ${m.role}`}><span>{m.role==="patient"?"You":"OnKo AI"}</span><p>{m.text}</p>{m.role==="ai"&&m.evidence?.length?<div className="ai-companion-evidence"><strong>Based on your record</strong>{m.evidence.map((e,j)=><span key={j}>• {e}</span>)}</div>:null}{m.role==="ai"&&m.limitations?.length?<div className="ai-companion-limitations"><strong>Important</strong>{m.limitations.map((x,j)=><span key={j}>• {x}</span>)}</div>:null}</article>):<div className="ai-companion-empty"><strong>Ask your first question</strong><span>For example: “When is my next appointment?” or “What milestones are currently pending?”</span></div>}</div>
 <div className="ai-companion-composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} placeholder="Ask about your recorded care journey…" rows={3}/><button onClick={send} disabled={!draft.trim()||loading}>{loading?"Thinking…":"Ask OnKo AI"}</button></div></div></div>{error&&<p className="patient-directory-error">{error}</p>}</section>;
}