import type {PatientInsightOutput} from "./types";

const schema={type:"object",properties:{historySummary:{type:"string"},appointmentSummary:{type:"string"},careJourneySummary:{type:"string"},engagementSummary:{type:"string"},signals:{type:"array",items:{type:"string"}},limitations:{type:"array",items:{type:"string"}}},required:["historySummary","appointmentSummary","careJourneySummary","engagementSummary","signals","limitations"]};

function buildPrompt(context:unknown){return `You are an AI care-workflow assistant for a cancer-care coordination platform. Summarize only the supplied longitudinal record. Do NOT diagnose, interpret reports, recommend treatment, prescribe, calculate clinical risk, or change care plans. Engagement signals must be observable operational patterns only, such as overdue milestones, missed appointments, open queries, or follow-up timing. Never infer a medical conclusion. Clearly state limitations. Return JSON matching this schema exactly.\\nSCHEMA:\\n${JSON.stringify(schema)}\\nPATIENT DATA:\\n${JSON.stringify(context)}`}

function validate(raw:string):PatientInsightOutput{const parsed=JSON.parse(raw) as PatientInsightOutput;if(!parsed.historySummary||!parsed.appointmentSummary||!parsed.careJourneySummary||!parsed.engagementSummary||!Array.isArray(parsed.signals)||!Array.isArray(parsed.limitations))throw new Error("AI output failed validation.");return parsed}

async function generateGemini(prompt:string,model:string,key:string){const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",responseSchema:schema}})});if(!response.ok)throw new Error(`Gemini request failed: ${response.status}`);const body=await response.json();const raw=body?.candidates?.[0]?.content?.parts?.[0]?.text;if(typeof raw!=="string")throw new Error("Gemini returned no structured output.");return validate(raw)}

async function generateGroq(prompt:string,model:string,key:string){const response=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:"system",content:"Return only valid JSON matching the requested schema. Follow all safety and scope constraints in the user prompt."},{role:"user",content:prompt}],temperature:0,response_format:{type:"json_object"}})});if(!response.ok)throw new Error(`Groq request failed: ${response.status}`);const body=await response.json();const raw=body?.choices?.[0]?.message?.content;if(typeof raw!=="string")throw new Error("Groq returned no structured output.");return validate(raw)}

export async function generatePatientInsight(context:unknown):Promise<{output:PatientInsightOutput;model:string}>{const prompt=buildPrompt(context);const geminiKey=process.env.GEMINI_API_KEY;const geminiModel=process.env.GEMINI_MODEL||"gemini-2.5-flash";const groqKey=process.env.GROQ_API_KEY;const groqModel=process.env.GROQ_MODEL||"llama-3.3-70b-versatile";let geminiError:unknown;if(geminiKey){try{return {output:await generateGemini(prompt,geminiModel,geminiKey),model:`gemini/${geminiModel}`}}catch(error){geminiError=error;console.error("Gemini patient insight generation failed; trying Groq fallback.",error)}}if(groqKey){try{return {output:await generateGroq(prompt,groqModel,groqKey),model:`groq/${groqModel}`}}catch(error){console.error("Groq patient insight generation failed.",error)}}if(geminiError)throw new Error("All configured AI providers failed.");throw new Error("No AI provider is configured.");}