import type {MedicalSource,MedicalChunk,RetrievalResult} from "@/types/rag";
const BASE="https://www.ebi.ac.uk/europepmc/webservices/rest/search";
const FULL_TEXT_BASE="https://www.ebi.ac.uk/europepmc/webservices/rest";
const CANCER_TERMS=/\\b(cancer|oncology|tumou?r|neoplasm|carcinoma|lymphoma|leukemia|leukaemia|melanoma|sarcoma|metastatic|chemotherapy|immunotherapy|radiotherapy|radiation therapy|survivorship|palliative)\\b/i;
function cancerQuery(query:string){return CANCER_TERMS.test(query)?query:`(${query}) AND (cancer OR oncology OR neoplasm OR carcinoma OR lymphoma OR leukemia OR melanoma OR sarcoma)`;}
function cleanXml(xml:string){return xml.replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#x([0-9A-Fa-f]+);/g,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/\\s+/g," ").trim();}
async function fetchOpenAccessText(pmcid?:string){if(!pmcid)return "";try{const r=await fetch(`${FULL_TEXT_BASE}/${encodeURIComponent(pmcid)}/fullTextXML`,{headers:{"Accept":"application/xml"},cache:"no-store"});if(!r.ok)return "";return cleanXml(await r.text())}catch{return "";}}
function splitText(text:string,size=1400){const out:string[]=[];for(let i=0;i<text.length;i+=size)out.push(text.slice(i,i+size));return out.filter(x=>x.trim());}
export async function retrieveMedicalLiterature(query:string,limit=5):Promise<RetrievalResult>{const q=query.trim();if(!q)throw new Error("Medical query is required.");const searchQuery=cancerQuery(q);const url=BASE+"?query="+encodeURIComponent(searchQuery)+"&format=json&pageSize="+Math.min(Math.max(limit,1),10)+"&resultType=core";const r=await fetch(url,{headers:{"Accept":"application/json"},cache:"no-store"});if(!r.ok)throw new Error("Europe PMC request failed: "+r.status);const body=await r.json();const results=(body?.resultList?.result??[]) as any[];const chunks:MedicalChunk[]=[];for(let i=0;i<results.length;i++){const x=results[i];const sourceId=x.pmcid||x.pmid||x.id||`europe-pmc-${i}`;const title=x.title||sourceId;const authors=(x.authorList?.author??[]).map((a:any)=>a.fullName||a.fullName).filter(Boolean).slice(0,8);const abstract=x.abstractText||"";const fullText=await fetchOpenAccessText(x.pmcid);const sourceText=fullText||[title,abstract].filter(Boolean).join("\n\n");const pieces=splitText(sourceText);pieces.slice(0,6).forEach((text,j)=>chunks.push({chunkId:`${sourceId}-chunk-${j+1}`,sourceId,text,section:fullText?"open-access-full-text":"title-and-abstract",rank:i*10+j+1,title,authors,publicationDate:x.firstPublicationDate||x.pubYear,abstract,pmid:x.pmid,pmcid:x.pmcid}));}return {query:q,chunks:chunks.sort((a,b)=>a.rank-b.rank).slice(0,Math.max(1,Math.min(limit*3,20))),provider:"europe-pmc",retrievedAt:new Date().toISOString()}}
export function toMedicalSources(retrieval:RetrievalResult):MedicalSource[]{const seen=new Set<string>();return retrieval.chunks.filter(c=>{if(seen.has(c.sourceId))return false;seen.add(c.sourceId);return true}).map(c=>({sourceId:c.sourceId,provider:"europe-pmc",title:c.title||c.sourceId,authors:c.authors||[],publicationDate:c.publicationDate,abstract:c.abstract,url:c.pmcid?`https://europepmc.org/articles/${encodeURIComponent(c.pmcid)}`:`https://europepmc.org/article/MED/${encodeURIComponent(c.pmid||c.sourceId)}`,pmid:c.pmid,pmcid:c.pmcid}))}